apiVersion: v1
kind: Secret

metadata:
  name: production-app-secret

type: Opaque

stringData:
  DB_USERNAME: {{ .Values.secret.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}
  API_KEY: {{ .Values.secret.API_KEY | quote }}
