filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /var/log/messages
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
    - /var/lib/docker/containers/*/*.log

output.logstash:
  hosts: ["172.31.10.115:5044"]


